### ISSUE TITLE
[meta] Ship v1.16

### ISSUE THREAD

**Issue by mjackson** [rackt/history#185]
I fixed `createLocation` in e1e0882389d47cea5f563871bee7400cd1953e59 and added the deprecation warnings for the `state` arg.

At this point I'd like to ship a version 1.16 that doesn't emit all the warnings. Then we can ship a router version 1.0.3 that uses it as a peer dep and stop breaking people's builds. I think the easiest way to do this is to just comment out all the warnings in history. This will at least get us back to a place where people who used `history: "^1.15.0"` in their package.json have a build that works.

**Comment by mjackson** [comment]
I pushed work for this in https://github.com/rackt/history/tree/1.16-no-warnings

**Comment by mjackson** [comment]
BTW, this is relevant to fixing https://github.com/rackt/react-router/issues/2682

**Comment by ryanflorence** [comment]
This looks great.

React Router 1.0.2 fixed the issue for people who are doing a fresh npm2 or npm3 install of react router.

History 0.16 will fix the issue for

- people who are using npm3 and do a non-versioned `npm install history`
- people who have a pinned react router at 1.0.0 or 1.0.1

Then we just leave 0.16 out there forever, and do the new strategy (new API with backwards compat deprecation and warnings are in a new major version) moving forward.

**Comment by taion** [comment]
:+1: to this, I think this is the cleanest way we can set things up for now.

That said, I'd think it'd be okay to do 1.17.x with the deprecation warnings as long as we release it w/React Router at the same time. The inconvenience this time around was just that users had no way to fix the deprecation warnings.

Sort of like the parent/owner context stuff in React 0.13.

**Comment by ryanflorence** [comment]
If we ship 1.17 with warnings then people with pinned routers at <1.0.2 will still have issues.

**Comment by taion** [comment]
I think at that point we should be willing to say "tough luck" if they pin to 1.0.x of React Router but let the minor version of `history` float.

**Comment by mjackson** [comment]
I think we need to ship 2.0 with warnings. 3.0 will remove them all.

**Comment by geowarin** [comment]
I'm still getting a warning from the render method of <Link />

```
Warning: the query argument to createHref is deprecated; use a location descriptor instead
```

Apparently it has be [fixed](https://github.com/rackt/react-router/commit/d9fb509ad9ad9e9ef369939df33247aa0e8fe657) but this means that we still have to wait for a new version of the router, isn't it?
